version: '2'
services:
  nginx:
    image: stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "gene.iobio:/usr/share/nginx/html:ro"
    depends_on:
      - af

  af:
    image: qiaoy/iobio.af
